{"level":"error","message":"error error","stack":"Error: error\n    at Object.<anonymous> (C:\\users\\user\\desktop\\nodejs-course\\vidly\\index.js:29:7)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:790:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"error error","stack":"Error: error\n    at Object.<anonymous> (C:\\users\\user\\desktop\\nodejs-course\\vidly\\index.js:31:7)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:790:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"info","message":"Connected to the database."}
{"level":"info","message":"Connected to the database."}
{"level":"info","message":"Connected to the database."}
